apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: togglemaster

spec:
  restartPolicy: Never

  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command:
      - sleep
      - "3600"
